### PR TITLE
new config, local deployment scripts, edited readme, scripts to ts

### PR DESCRIPTION
**Pull request by ernestpascual**
## Description of Changes
- converted deploy scripts from js to ts
- added local environment config for hardhat
- removed sample-script.js
- added a script to use hardhat node
- added a script to use your preferred local node to deploy into

No Jira Ticket

## How To Test
Prerequisites of each run script:
- for `deploy:hardhat `- no prerequisite
- for `deploy:local` - run a node first (yarn/npm run node or ganache)
- for kovan scripts - no prerequisite

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [ ] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by ernestpascual** [comment]
hi @bitcoinbrisbane , for context @ctverceles was not able to run the deploy scripts properly so I also converted it to ts and did some additional config for local development. let me know if this affects your current tasks too, thanks!

**Comment by ctverceles** [comment]
Thanks @ernestpascual . yes something made its way into develop and was blocking reviews for https://github.com/HaloDAO/pool-worker/pull/2/, https://github.com/HaloDAO/pool-worker/pull/1, https://github.com/HaloDAO/rewards-worker/pull/2 - thanks for the quick fix! Checking now

**Comment by ctverceles** [comment]
@ernestpascual are you getting this when running `npx hardhat test` 
image

**Comment by ctverceles** [comment]
Unit tests all working on my end now @ernestpascual

**Review by ctverceles — APPROVED** [review]

**Pull request merged**
