### PR TITLE
Feature/hdf 71

### PR DESCRIPTION
**Pull request by bitcoinbrisbane**
## Description of Changes

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-71)

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by schystz** [comment]
Hi @bitcoinbrisbane , can you pls change the base branch for this PR to `develop`?

**Comment by bitcoinbrisbane** [comment]
> Hi @bitcoinbrisbane , can you pls change the base branch for this PR to `develop`?

Sure!

**Comment by ctverceles** [comment]
At first i was getting the ff errs until i added `import { sleep } from './utils/math'` onto this line https://github.com/HaloDAO/halo-rewards/blob/313899394053b828ba803f1bcb1d438dba23c4ce/test/halohalo.ts#L5

Screen Shot 2021-04-21 at 2 20 54 PM

After that everything ran smoothly, 39 passing tests and 17 pending tests (are we going to "unskip" these tests before merging @bitcoinbrisbane or leave these skipped for now?)

I'll go through the logic between meetings to familiarize as well

**Review by ctverceles — APPROVED** [review]
Just that last comment but once the commit comes in, should be good! https://github.com/HaloDAO/halo-rewards/pull/11#issuecomment-823817008

**Comment by mystbrent** [comment]
After adding import of sleep in halohalo.ts all tests run perfectly. Tests may be affected once implementation of HDF-94 is added.

**Review by mystbrent — APPROVED** [review]

**Comment by ernestpascual** [comment]
> At first i was getting the ff errs until i added `import { sleep } from './utils/math'` onto this line
> 
> https://github.com/HaloDAO/halo-rewards/blob/313899394053b828ba803f1bcb1d438dba23c4ce/test/halohalo.ts#L5
> 
> Screen Shot 2021-04-21 at 2 20 54 PM
> 
> After that everything ran smoothly, 39 passing tests and 17 pending tests (are we going to "unskip" these tests before merging @bitcoinbrisbane or leave these skipped for now?)
> 
> I'll go through the logic between meetings to familiarize as well

I actually tried using ` await time.increase(sleepTime)` here and it works. just need to work the calculations. I got this from the rewards contract refactor

**Review by ernestpascual — APPROVED** [review]

**Review by ernestpascual — COMMENTED** [review]
reward tests looking good, thanks @bitcoinbrisbane will probably use the same patterns on my branch as well.

**Comment by ctverceles** [comment]
@bitcoinbrisbane i got this, this time. not sure if this is what you mentioned? 
image

**Review by ctverceles — APPROVED** [review]

**Review by ernestpascual — APPROVED** [review]
looking good!

**Pull request merged**
