### PR TITLE
separated deploy scripts for local and kovan deployment

### PR DESCRIPTION
**Pull request by ernestpascual**
## Description of Changes

Separated the deploy scripts for kovan and local deployment for the use of our workers. I added a mock LP deployment in the local scripts for local environment testing.

No Jira Ticket

## How To Test
- `yarn/npm run deploy:hardhat`  (to check everything compiles and works well in an isolated hardhat node)
- `yarn/npm run deploy:local ` (to check deployment in the current running node)
- run any kovan deployment script (to check kovan deployment) 
- Note: When doing `deployOnlyRewards` make sure you are who deployed the HALO Token for minting to be successful on the last step.

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [ ] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by mystbrent** [comment]
### Reviewers Checklist:

- [x] Code is readable and understandable; any unclear parts have explanations
- [x] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally


Script deployAllLocal.ts and deployAllKovan are working great.

Ran tests in my local and I have this errors.

title

**Review by ctverceles — APPROVED** [review]
- [x]  Code is readable and understandable; any unclear parts have explanations
- [x]  I have successfully ran tests locally

[deployAllLocal](https://github.com/HaloDAO/halo-rewards/blob/others/separate-scripts/scripts/deployAllLocal.ts) and [deployAllKovan](https://github.com/HaloDAO/halo-rewards/blob/others/separate-scripts/scripts/deployAllKovan.ts) working for me! thanks @ernestpascual

**Comment by ernestpascual** [comment]
> ### Reviewers Checklist:
> * [x]  Code is readable and understandable; any unclear parts have explanations
> * [x]  UI/UX changes match the corresponding figma/other design resources, if applicable
> * [ ]  I have successfully ran tests locally
> 
> Script deployAllLocal.ts and deployAllKovan are working great.
> 
> Ran tests in my local and I have this typescript errors.
> 
> title

this is running `yarn/npm test` or `npx hardhat test` ? i don't see these in my local.

**Comment by ernestpascual** [comment]
i guess most of the test scripts are untouched from krishab's end, we did not really change them that much. i guess we're still waiting for the refactoring from Lucas end to fix some stuff there.

**Pull request merged**
